var l,m=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function s(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a){return a[ga]||(a[ga]=++ia)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ia=0;function ja(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return x.apply(null,arguments)}
function la(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var z=Date.now||function(){return+new Date};function A(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c};var ma={zb:!0},na={Ab:!0};var oa;function pa(a){Error.captureStackTrace?Error.captureStackTrace(this,pa):this.stack=Error().stack||"";a&&(this.message=String(a))}A(pa,Error);pa.prototype.name="CustomError";function qa(a,b){for(var c=a.split("%s"),d="",f=Array.prototype.slice.call(arguments,1);f.length&&1<c.length;)d+=c.shift()+f.shift();return d+c.join("%s")}function ra(a,b){if(b)return a.replace(sa,"&amp;").replace(ta,"&lt;").replace(ua,"&gt;").replace(va,"&quot;");if(!wa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(sa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ta,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ua,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(va,"&quot;"));return a}
var sa=/&/g,ta=/</g,ua=/>/g,va=/\"/g,wa=/[&<>\"]/;function xa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})}function ya(a){var b=v(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};function za(a,b){b.unshift(a);pa.call(this,qa.apply(null,b));b.shift()}A(za,pa);za.prototype.name="AssertionError";function Aa(a,b){throw new za("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var B=Array.prototype,Ba=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(v(a))return v(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function Da(a,b,c){for(var d=v(a)?a.split(""):a,f=a.length-1;0<=f;--f)f in d&&b.call(c,d[f],f,a)}
var Ea=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=v(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(f[e++]=k)}return f},Fa=B.map?function(a,b,c){return B.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),e=v(a)?a.split(""):a,g=0;g<d;g++)g in e&&(f[g]=b.call(c,e[g],g,a));return f};function C(a,b){return 0<=Ba(a,b)}function Ga(a,b){var c=Ba(a,b),d;(d=0<=c)&&B.splice.call(a,c,1);return d}
function Ha(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ia(a,b,c){return 2>=arguments.length?B.slice.call(a,b):B.slice.call(a,b,c)};function Ja(a){a=a.className;return v(a)&&a.match(/\S+/g)||[]}function Ka(a,b){var c=Ja(a),d=Ia(arguments,1),f=c.length+d.length;La(c,d);a.className=c.join(" ");return c.length==f}function Ma(a,b){var c=Ja(a),d=Ia(arguments,1),c=Na(c,d);a.className=c.join(" ")}function La(a,b){for(var c=0;c<b.length;c++)C(a,b[c])||a.push(b[c])}function Na(a,b){return Ea(a,function(a){return!C(b,a)})}
function Oa(a,b,c){var d=Ja(a);v(b)?Ga(d,b):s(b)&&(d=Na(d,b));v(c)&&!C(d,c)?d.push(c):s(c)&&La(d,c);a.className=d.join(" ")};function Pa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Qa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ra(){var a=Sa,b;for(b in a)return!1;return!0}var Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ua(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Ta.length;e++)c=Ta[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Va,Wa,Za,$a,ab;function bb(){return m.navigator?m.navigator.userAgent:null}function cb(){return m.navigator}$a=Za=Wa=Va=!1;var db;if(db=bb()){var eb=cb();Va=0==db.lastIndexOf("Opera",0);Wa=!Va&&(-1!=db.indexOf("MSIE")||-1!=db.indexOf("Trident"));Za=!Va&&-1!=db.indexOf("WebKit");$a=!Va&&!Za&&!Wa&&"Gecko"==eb.product}var fb=Va,D=Wa,F=$a,G=Za,gb=cb();ab=-1!=(gb&&gb.platform||"").indexOf("Mac");var hb=!!cb()&&-1!=(cb().appVersion||"").indexOf("X11");
function ib(){var a=m.document;return a?a.documentMode:void 0}var jb;a:{var kb="",lb;if(fb&&m.opera)var mb=m.opera.version,kb="function"==typeof mb?mb():mb;else if(F?lb=/rv\:([^\);]+)(\)|;)/:D?lb=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:G&&(lb=/WebKit\/(\S+)/),lb)var nb=lb.exec(bb()),kb=nb?nb[1]:"";if(D){var ob=ib();if(ob>parseFloat(kb)){jb=String(ob);break a}}jb=kb}var pb={};
function H(a){var b;if(!(b=pb[a])){b=0;for(var c=String(jb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",h=d[e]||"",k=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var r=k.exec(g)||["","",""],n=q.exec(h)||["","",""];if(0==r[0].length&&0==n[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==n[1].length?0:parseInt(n[1],10))?-1:(0==r[1].length?0:parseInt(r[1],
10))>(0==n[1].length?0:parseInt(n[1],10))?1:0)||((0==r[2].length)<(0==n[2].length)?-1:(0==r[2].length)>(0==n[2].length)?1:0)||(r[2]<n[2]?-1:r[2]>n[2]?1:0)}while(0==b)}b=pb[a]=0<=b}return b}var qb=m.document,rb=qb&&D?ib()||("CSS1Compat"==qb.compatMode?parseInt(jb,10):5):void 0;function sb(a,b){this.width=a;this.height=b}sb.prototype.c=function(){return new sb(this.width,this.height)};sb.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};sb.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var tb=!D||D&&9<=rb;!F&&!D||D&&D&&9<=rb||F&&H("1.9.1");var ub=D&&!H("9");function I(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}I.prototype.c=function(){return new I(this.x,this.y)};I.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function vb(a,b){return new I(a.x-b.x,a.y-b.y)}I.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function J(a){return a?new wb(K(a)):oa||(oa=new wb)}function xb(a){var b=document;return v(a)?b.getElementById(a):a}function yb(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):zb("*",a,b)}function Ab(a,b){var c=b||document,d=null;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):yb(a,b)[0])||null}
function zb(a,b,c){var d=document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},f=0,e=0,g;g=c[e];e++)a==g.nodeName&&(d[f++]=g);d.length=f;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(e=f=0;g=c[e];e++)a=g.className,"function"==typeof a.split&&C(a.split(/\s+/),b)&&(d[f++]=g);d.length=f;return d}return c}
function Bb(a,b){Pa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Cb?a.setAttribute(Cb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Db(a){return G||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Eb(a,b,c){function d(c){c&&b.appendChild(v(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(!ca(e)||ea(e)&&0<e.nodeType)d(e);else{var g;a:{if(e&&"number"==typeof e.length){if(ea(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if(da(e)){g="function"==typeof e.item;break a}}g=!1}Ca(g?Ha(e):e,d)}}}
function L(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function K(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Fb(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild(K(a).createTextNode(String(b)))}}var Gb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Hb={IMG:" ",BR:"\n"};
function Ib(a){if(ub&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Jb(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");ub||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Jb(a,b,c){if(!(a.nodeName in Gb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Hb)b.push(Hb[a.nodeName]);else for(a=a.firstChild;a;)Jb(a,b,c),a=a.nextSibling}function Kb(a){return Lb(a,function(a){return C(Ja(a),"pager")},!0)}function Lb(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var f=0;a&&(c||f<=d);){if(b(a))return a;a=a.parentNode;f++}return null}function wb(a){this.c=a||m.document||document}
wb.prototype.e=function(a,b,c){var d=this.c,f=arguments,e=f[0],g=f[1];if(!tb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',ra(g.name),'"');if(g.type){e.push(' type="',ra(g.type),'"');var h={};Ua(h,g);delete h.type;g=h}e.push(">");e=e.join("")}e=d.createElement(e);g&&(v(g)?e.className=g:s(g)?Ka.apply(null,[e].concat(g)):Bb(e,g));2<f.length&&Eb(d,e,f);return e};function Mb(a){return"CSS1Compat"==a.c.compatMode}
function Nb(a){var b=a.c;a=Db(b);b=b.parentWindow||b.defaultView;return D&&H("10")&&b.pageYOffset!=a.scrollTop?new I(a.scrollLeft,a.scrollTop):new I(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}wb.prototype.contains=L;function Ob(a){var b;b=J().c.createElement("DIV");a=Pb(a(Qb,void 0,void 0));a.match(Rb);b.innerHTML=a;return 1==b.childNodes.length&&(a=b.firstChild,1==a.nodeType)?a:b}function Pb(a){if(!ea(a))return String(a);Aa("Soy template output is unsafe for use as HTML: "+a);return"zSoyz"}var Rb=/^<(body|caption|col|colgroup|head|html|tr|td|tbody|thead|tfoot)>/i,Qb={};function M(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}M.prototype.c=function(){return new M(this.top,this.right,this.bottom,this.left)};M.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};M.prototype.contains=function(a){return this&&a?a instanceof M?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
function Sb(a,b){var c=b.x<a.left?b.x-a.left:b.x>a.right?b.x-a.right:0,d=b.y<a.top?b.y-a.top:b.y>a.bottom?b.y-a.bottom:0;return Math.sqrt(c*c+d*d)}M.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function O(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}O.prototype.c=function(){return new O(this.left,this.top,this.width,this.height)};function Tb(a){return new M(a.top,a.left+a.width,a.top+a.height,a.left)}O.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
O.prototype.contains=function(a){return a instanceof O?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};O.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Ub(a,b,c){v(b)?Vb(a,c,b):Pa(b,la(Vb,a))}function Vb(a,b,c){(c=Wb(a,c))&&(a.style[c]=b)}function Wb(a,b){var c=xa(b);if(void 0===a.style[c]){var d=(G?"Webkit":F?"Moz":D?"ms":fb?"O":null)+ya(b);if(void 0!==a.style[d])return d}return c}function P(a,b){var c=K(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function Q(a,b){return P(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Xb(a){a=a?K(a):document;return!D||D&&9<=rb||Mb(J(a))?a.documentElement:a.body}function Yb(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}D&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Zb(a){if(D&&!(D&&8<=rb))return a.offsetParent;var b=K(a),c=Q(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Q(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function $b(a){for(var b=new M(0,Infinity,Infinity,0),c=J(a),d=c.c.body,f=c.c.documentElement,e=Db(c.c);a=Zb(a);)if(!(D&&0==a.clientWidth||G&&0==a.clientHeight&&a==d||a==d||a==f||"visible"==Q(a,"overflow"))){var g=S(a),h;h=a;if(F&&!H("1.9")){var k=parseFloat(P(h,"borderLeftWidth"));if(ac(h))var q=h.offsetWidth-h.clientWidth-k-parseFloat(P(h,"borderRightWidth")),k=k+q;h=new I(k,parseFloat(P(h,"borderTopWidth")))}else h=new I(h.clientLeft,h.clientTop);g.x+=h.x;g.y+=h.y;b.top=Math.max(b.top,g.y);b.right=
Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=e.scrollLeft;e=e.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,e);c=(c.c.parentWindow||c.c.defaultView||window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new sb(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,e+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}
function S(a){var b,c=K(a),d=Q(a,"position"),f=F&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),e=new I(0,0),g=Xb(c);if(a==g)return e;if(a.getBoundingClientRect)b=Yb(a),a=Nb(J(c)),e.x=b.left+a.x,e.y=b.top+a.y;else if(c.getBoxObjectFor&&!f)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),e.x=b.screenX-a.screenX,e.y=b.screenY-a.screenY;else{b=a;do{e.x+=b.offsetLeft;e.y+=b.offsetTop;b!=a&&(e.x+=b.clientLeft||0,e.y+=b.clientTop||0);if(G&&
"fixed"==Q(b,"position")){e.x+=c.body.scrollLeft;e.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(fb||G&&"absolute"==d)e.y-=c.body.offsetTop;for(b=a;(b=Zb(b))&&b!=c.body&&b!=g;)e.x-=b.scrollLeft,fb&&"TR"==b.tagName||(e.y-=b.scrollTop)}return e}function bc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function cc(a){var b=dc;if("none"!=Q(a,"display"))return b(a);var c=a.style,d=c.display,f=c.visibility,e=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=e;c.visibility=f;return a}function dc(a){var b=a.offsetWidth,c=a.offsetHeight,d=G&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Yb(a),new sb(a.right-a.left,a.bottom-a.top)):new sb(b,c)}function ec(a){var b=S(a);a=cc(a);return new O(b.x,b.y,a.width,a.height)}
function fc(a,b){a.style.display=b?"":"none"}function ac(a){return"rtl"==Q(a,"direction")}function gc(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var f=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return f}function hc(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?gc(a,c):0}var ic={thin:2,medium:4,thick:6};
function jc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in ic?ic[c]:gc(a,c)}var kc=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;var lc;function mc(a,b){s(b)||(b=[b]);var c=Fa(b,function(a){return v(a)?a:a.mb+" "+a.duration+"s "+a.timing+" "+a.cb+"s"});Ub(a,"transition",c.join(","))}
function nc(){if(void 0===lc)if(D)lc=H("10.0");else{var a=document.createElement("div"),b=G?"-webkit":F?"-moz":D?"-ms":fb?"-o":null;a.innerHTML='<div style="'+(b?b+"-transition:opacity 1s linear;":"")+'transition:opacity 1s linear;">';a=a.firstChild;b=a.style[xa("transition")];lc=""!=("undefined"!==typeof b?b:a.style[Wb(a,"transition")]||"")}return lc};function oc(a,b){null!=a&&this.c.apply(this,arguments)}oc.prototype.e="";oc.prototype.c=function(a,b,c){this.e+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.e+=arguments[d];return this};oc.prototype.clear=function(){this.e=""};oc.prototype.toString=function(){return this.e};/*
 Portions of this code are from the google-caja project, received by
 Google under the Apache license (http://code.google.com/p/google-caja/).
 All other code is Copyright 2009 Google, Inc. All Rights Reserved.

// Copyright (C) 2006 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

*/
function pc(){}
var qc={wb:"<",ub:">",sb:"&",xb:" ",yb:'"',tb:"'"},rc={a:0,abbr:0,acronym:0,address:0,applet:16,area:2,b:0,base:18,basefont:18,bdo:0,big:0,blockquote:0,body:49,br:2,button:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,dd:1,del:0,dfn:0,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,font:0,form:0,frame:18,frameset:16,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:49,hr:2,html:49,i:0,iframe:20,img:2,input:2,ins:0,isindex:18,kbd:0,label:0,legend:0,li:1,link:18,map:0,menu:0,meta:18,noframes:20,noscript:20,object:16,
ol:0,optgroup:0,option:1,p:1,param:18,pre:0,q:0,s:0,samp:0,script:20,select:0,small:0,span:0,strike:0,strong:0,style:20,sub:0,sup:0,table:0,tbody:1,td:1,textarea:8,tfoot:1,th:1,thead:1,title:24,tr:1,tt:0,u:0,ul:0,"var":0},sc=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,tc=/</g,uc=/>/g,vc=/\0/g,wc=/&(#\d+|#x[0-9A-Fa-f]+|\w+);/g,xc=/^#(\d+)$/,yc=/^#x([0-9A-Fa-f]+)$/,zc=RegExp("^\\s*(?:(?:([a-z][a-z-]*)(\\s*=\\s*(\"[^\"]*\"|'[^']*'|(?=[a-z][a-z-]*\\s*=)|[^>\"'\\s]*))?)|(/?>)|[^a-z\\s>]+)","i"),Ac=
RegExp("^(?:&(\\#[0-9]+|\\#[x][0-9a-f]+|\\w+);|<[!]--[\\s\\S]*?--\x3e|<!\\w[^>]*>|<\\?[^>*]*>|<(/)?([a-z][a-z0-9]*)|([^<&>]+)|([<&>]))","i");pc.prototype.c=function(a){a=a.toLowerCase();if(qc.hasOwnProperty(a))return qc[a];var b=a.match(xc);return b?String.fromCharCode(parseInt(b[1],10)):(b=a.match(yc))?String.fromCharCode(parseInt(b[1],16)):""};function Bc(){};function Cc(){}A(Cc,Bc);l=Cc.prototype;l.na=null;l.G=null;l.ca=null;l.Ma=function(a){this.ca.pop();this.G.c("</",a,">")};function Dc(a,b){if(-1!=b.indexOf("\n")){var c=b.split("\n"),d=c.length-1;Ca(c,function(a,b){0!=b&&Ca(this.ca,function(a){this.G.c("<",a.Wa,a.attributes,">")},this);this.G.c(a);b!=d&&(Da(this.ca,function(a){this.G.c("</",a.Wa,">")},this),this.na.push(this.G.toString()),this.G=new oc)},a)}else a.G.c(b)}l.nb=function(){};
l.Va=function(a,b){for(var c=new oc,d=0;d<b.length;d+=2)c.c(" ",b[d],'="',ra(b[d+1],!1),'"');c=c.toString();this.ca.push({Wa:a,attributes:c});this.G.c("<",a,c,">")};function Ec(){0!=Fc&&fa(this)}var Fc=0;var Gc="closure_listenable_"+(1E6*Math.random()|0);function Hc(a){try{return!(!a||!a[Gc])}catch(b){return!1}}var Ic=0;function Jc(a,b,c,d,f){this.N=a;this.c=null;this.src=b;this.type=c;this.capture=!!d;this.ka=f;this.Oa=++Ic;this.V=this.fa=!1}function Kc(a){a.V=!0;a.N=null;a.c=null;a.src=null;a.ka=null};function Lc(a){this.src=a;this.c={};this.e=0}function Mc(a,b,c,d,f,e){var g=a.c[b];g||(g=a.c[b]=[],a.e++);var h=Nc(g,c,f,e);-1<h?(a=g[h],d||(a.fa=!1)):(a=new Jc(c,a.src,b,!!f,e),a.fa=d,g.push(a));return a}function Oc(a,b){var c=b.type;if(!(c in a.c))return!1;var d=Ga(a.c[c],b);d&&(Kc(b),0==a.c[c].length&&(delete a.c[c],a.e--));return d}function Pc(a,b,c,d,f){a=a.c[b];b=-1;a&&(b=Nc(a,c,d,f));return-1<b?a[b]:null}
function Nc(a,b,c,d){for(var f=0;f<a.length;++f){var e=a[f];if(!e.V&&e.N==b&&e.capture==!!c&&e.ka==d)return f}return-1};var Qc=!D||D&&9<=rb,Rc=D&&!H("9");!G||H("528");F&&H("1.9b")||D&&H("8")||fb&&H("9.5")||G&&H("528");F&&!H("8")||D&&H("9");function T(a,b){this.type=a;this.c=this.target=b}T.prototype.e=!1;T.prototype.Ua=!0;T.prototype.xa=function(){this.Ua=!1};function Sc(a){Sc[" "](a);return a}Sc[" "]=aa;function Tc(a,b){if(a){var c=this.type=a.type;T.call(this,c);this.target=a.target||a.srcElement;this.c=b;var d=a.relatedTarget;if(d){if(F){var f;a:{try{Sc(d.nodeName);f=!0;break a}catch(e){}f=!1}f||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.Q=d;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.button=a.button;this.keyCode=a.keyCode||0;this.ctrlKey=a.ctrlKey;this.Na=a;a.defaultPrevented&&this.xa();delete this.e}}
A(Tc,T);l=Tc.prototype;l.target=null;l.Q=null;l.clientX=0;l.clientY=0;l.button=0;l.keyCode=0;l.ctrlKey=!1;l.Na=null;l.xa=function(){Tc.B.xa.call(this);var a=this.Na;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Rc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Uc="closure_lm_"+(1E6*Math.random()|0),Vc={},Wc=0;function U(a,b,c,d,f){if(s(b)){for(var e=0;e<b.length;e++)U(a,b[e],c,d,f);return null}c=Xc(c);return Hc(a)?a.D(b,c,d,f):Yc(a,b,c,!1,d,f)}function Yc(a,b,c,d,f,e){if(!b)throw Error("Invalid event type");var g=!!f,h=Zc(a);h||(a[Uc]=h=new Lc(a));c=Mc(h,b,c,d,f,e);if(c.c)return c;d=$c();c.c=d;d.src=a;d.N=c;a.addEventListener?a.addEventListener(b,d,g):a.attachEvent(b in Vc?Vc[b]:Vc[b]="on"+b,d);Wc++;return c}
function $c(){var a=ad,b=Qc?function(c){return a.call(b.src,b.N,c)}:function(c){c=a.call(b.src,b.N,c);if(!c)return c};return b}function bd(a,b,c,d,f){if(s(b))for(var e=0;e<b.length;e++)bd(a,b[e],c,d,f);else c=Xc(c),Hc(a)?Mc(a.M,String(b),c,!0,d,f):Yc(a,b,c,!0,d,f)}function V(a,b,c,d,f){if(s(b))for(var e=0;e<b.length;e++)V(a,b[e],c,d,f);else c=Xc(c),Hc(a)?a.ua(b,c,d,f):a&&(a=Zc(a))&&(b=Pc(a,b,c,!!d,f))&&cd(b)}
function cd(a){if("number"==typeof a||!a||a.V)return!1;var b=a.src;if(Hc(b))return Oc(b.M,a);var c=a.type,d=a.c;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(c in Vc?Vc[c]:Vc[c]="on"+c,d);Wc--;(c=Zc(b))?(Oc(c,a),0==c.e&&(c.src=null,b[Uc]=null)):Kc(a);return!0}function dd(a,b,c,d){var f=1;if(a=Zc(a))if(b=a.c[b])for(b=Ha(b),a=0;a<b.length;a++){var e=b[a];e&&e.capture==c&&!e.V&&(f&=!1!==ed(e,d))}return Boolean(f)}
function ed(a,b){var c=a.N,d=a.ka||a.src;a.fa&&cd(a);return c.call(d,b)}
function ad(a,b){if(a.V)return!0;if(!Qc){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,f;f=c.shift();)if(null!=d[f])d=d[f];else{c=null;break a}c=d}f=c;c=new Tc(f,this);d=!0;if(!(0>f.keyCode||void 0!=f.returnValue)){a:{var e=!1;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==f.returnValue)f.returnValue=!0}f=[];for(e=c.c;e;e=e.parentNode)f.push(e);for(var e=a.type,h=f.length-1;!c.e&&0<=h;h--)c.c=f[h],d&=dd(f[h],e,!0,c);for(h=0;!c.e&&h<f.length;h++)c.c=f[h],d&=dd(f[h],e,!1,
c)}return d}return ed(a,new Tc(b,this))}function Zc(a){a=a[Uc];return a instanceof Lc?a:null}var fd="__closure_events_fn_"+(1E9*Math.random()>>>0);function Xc(a){return da(a)?a:a[fd]||(a[fd]=function(b){return a.handleEvent(b)})};function W(){Ec.call(this);this.M=new Lc(this);this.Ya=this}A(W,Ec);W.prototype[Gc]=!0;W.prototype.removeEventListener=function(a,b,c,d){V(this,a,b,c,d)};function X(a,b){var c=a.Ya,d=b,f=d.type||d;if(v(d))d=new T(d,c);else if(d instanceof T)d.target=d.target||c;else{var e=d,d=new T(f,c);Ua(d,e)}e=!0;d.e||(c=d.c=c,e=gd(c,f,!0,d)&&e,d.e||(e=gd(c,f,!1,d)&&e));return e}W.prototype.D=function(a,b,c,d){return Mc(this.M,String(a),b,!1,c,d)};
W.prototype.ua=function(a,b,c,d){var f;f=this.M;a=String(a);if(a in f.c){var e=f.c[a];b=Nc(e,b,c,d);-1<b?(Kc(e[b]),B.splice.call(e,b,1),0==e.length&&(delete f.c[a],f.e--),f=!0):f=!1}else f=!1;return f};function gd(a,b,c,d){b=a.M.c[String(b)];if(!b)return!0;b=Ha(b);for(var f=!0,e=0;e<b.length;++e){var g=b[e];if(g&&!g.V&&g.capture==c){var h=g.N,k=g.ka||g.src;g.fa&&Oc(a.M,g);f=!1!==h.call(k,d)&&f}}return f&&!1!=d.Ua};function hd(a,b){W.call(this);this.f=a||1;this.e=b||m;this.k=x(this.n,this);this.m=z()}A(hd,W);hd.prototype.h=!1;hd.prototype.c=null;hd.prototype.n=function(){if(this.h){var a=z()-this.m;0<a&&a<0.8*this.f?this.c=this.e.setTimeout(this.k,this.f-a):(this.c&&(this.e.clearTimeout(this.c),this.c=null),X(this,id),this.h&&(this.c=this.e.setTimeout(this.k,this.f),this.m=z()))}};hd.prototype.stop=function(){this.h=!1;this.c&&(this.e.clearTimeout(this.c),this.c=null)};var id="tick";
function jd(a,b,c){if(da(a))c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<b?-1:m.setTimeout(a,b||0)};function kd(a,b,c){Ec.call(this);this.e=a;this.k=b||0;this.h=c;this.f=x(this.m,this)}A(kd,Ec);kd.prototype.c=0;function ld(a){a.stop();a.c=jd(a.f,a.k)}kd.prototype.stop=function(){0!=this.c&&m.clearTimeout(this.c);this.c=0};kd.prototype.m=function(){this.c=0;this.e&&this.e.call(this.h)};var Sa={},md=null;function nd(a){a=fa(a);delete Sa[a];Ra()&&md&&md.stop()}function od(){md||(md=new kd(function(){pd()},20));var a=md;0!=a.c||ld(a)}function pd(){var a=z();Pa(Sa,function(b){qd(b,a)});Ra()||od()};function rd(){W.call(this);this.c=sd;this.w=this.e=null}A(rd,W);var sd=0;rd.prototype.m=function(){this.C("begin")};rd.prototype.h=function(){this.C("end")};rd.prototype.C=function(a){X(this,a)};function td(a,b,c,d){rd.call(this);if(!s(a)||!s(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.k=a;this.F=b;this.duration=c;this.A=d;this.f=[]}A(td,rd);l=td.prototype;l.I=0;
l.ya=function(a){if(a||this.c==sd)this.I=0,this.f=this.k;else if(1==this.c)return!1;nd(this);this.e=a=z();-1==this.c&&(this.e-=this.duration*this.I);this.w=this.e+this.duration;this.I||this.m();this.C("play");-1==this.c&&this.C("resume");this.c=1;var b=fa(this);b in Sa||(Sa[b]=this);od();qd(this,a);return!0};l.stop=function(a){nd(this);this.c=sd;a&&(this.I=1);ud(this,this.I);this.C("stop");this.h()};
function qd(a,b){a.I=(b-a.e)/(a.w-a.e);1<=a.I&&(a.I=1);ud(a,a.I);1==a.I?(a.c=sd,nd(a),a.C("finish"),a.h()):1==a.c&&a.Ea()}function ud(a,b){da(a.A)&&(b=a.A(b));a.f=Array(a.k.length);for(var c=0;c<a.k.length;c++)a.f[c]=(a.F[c]-a.k[c])*b+a.k[c]}l.Ea=function(){this.C("animate")};l.C=function(a){X(this,new vd(a,this))};function vd(a,b){T.call(this,a);this.x=b.f[0];this.y=b.f[1];this.duration=b.duration}A(vd,T);function Y(a,b,c,d,f){td.call(this,b,c,d,f);this.J=a}A(Y,td);Y.prototype.n=aa;Y.prototype.Ea=function(){this.n();Y.B.Ea.call(this)};Y.prototype.h=function(){this.n();Y.B.h.call(this)};Y.prototype.m=function(){this.n();Y.B.m.call(this)};function wd(a,b,c,d,f){"number"==typeof b&&(b=[b]);"number"==typeof c&&(c=[c]);Y.call(this,a,b,c,d,f);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");}A(wd,Y);
wd.prototype.n=function(){var a=this.f[0],b=this.J.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity="+100*a+")")};function xd(a,b,c){wd.call(this,a,1,0,b,c)}A(xd,wd);function yd(a,b,c){wd.call(this,a,0,1,b,c)}A(yd,wd);function zd(a,b,c,d,f){rd.call(this);this.f=a;this.F=b;this.J=c;this.n=d;this.X=s(f)?f:[f]}A(zd,rd);zd.prototype.ya=function(){if(1==this.c)return!1;this.m();this.C("play");this.e=z();this.c=1;if(nc())return Ub(this.f,this.J),this.A=jd(this.U,void 0,this),!0;this.k(!1);return!1};zd.prototype.U=function(){mc(this.f,this.X);Ub(this.f,this.n);this.A=jd(x(this.k,this,!1),1E3*this.F)};zd.prototype.stop=function(){1==this.c&&this.k(!0)};
zd.prototype.k=function(a){Ub(this.f,"transition","");m.clearTimeout(this.A);Ub(this.f,this.n);this.w=z();this.c=sd;a?this.C("stop"):this.C("finish");this.h()};function Ad(a,b,c,d){return new zd(a,0.15,{opacity:c},{opacity:d},{mb:"opacity",duration:0.15,timing:b,cb:0})};function Bd(a,b,c,d,f,e,g,h){var k,q;if(k=c.offsetParent){var r="HTML"==k.tagName||"BODY"==k.tagName;r&&"static"==Q(k,"position")||(q=S(k),r||(r=(r=ac(k))&&F?-k.scrollLeft:!r||D&&H("8")||"visible"==Q(k,"overflowX")?k.scrollLeft:k.scrollWidth-k.clientWidth-k.scrollLeft,q=vb(q,new I(r,k.scrollTop))))}k=q||new I;q=ec(a);if(r=$b(a)){var n=new O(r.left,r.top,r.right-r.left,r.bottom-r.top),r=Math.max(q.left,n.left),t=Math.min(q.left+q.width,n.left+n.width);if(r<=t){var E=Math.max(q.top,n.top),n=Math.min(q.top+
q.height,n.top+n.height);E<=n&&(q.left=r,q.top=E,q.width=t-r,q.height=n-E)}}r=J(a);E=J(c);if(r.c!=E.c){var t=r.c.body,E=E.c.parentWindow||E.c.defaultView,n=new I(0,0),N=K(t)?K(t).parentWindow||K(t).defaultView:window,ha=t;do{var p;if(N==E)p=S(ha);else{p=ha;var y=void 0;if(p.getBoundingClientRect)y=Yb(p),y=new I(y.left,y.top);else var y=Nb(J(p)),u=S(p),y=new I(u.x-y.x,u.y-y.y);u=void 0;if(F&&!H(12)){u=void 0;u=void 0;D?u="-ms-transform":G?u="-webkit-transform":fb?u="-o-transform":F&&(u="-moz-transform");
var R=void 0;u&&(R=Q(p,u));R||(R=Q(p,"transform"));u=R?(p=R.match(kc))?new I(parseFloat(p[1]),parseFloat(p[2])):new I(0,0):new I(0,0);u=new I(y.x+u.x,y.y+u.y)}else u=y;p=u}n.x+=p.x;n.y+=p.y}while(N&&N!=E&&(ha=N.frameElement)&&(N=N.parent));t=vb(n,S(t));D&&!Mb(r)&&(t=vb(t,Nb(r)));q.left+=t.x;q.top+=t.y}a=(b&4&&ac(a)?b^2:b)&-5;b=new I(a&2?q.left+q.width:q.left,a&1?q.top+q.height:q.top);b=vb(b,k);f&&(b.x+=(a&2?-1:1)*f.x,b.y+=(a&1?-1:1)*f.y);var w;g&&(w=$b(c))&&(w.top-=k.y,w.right-=k.x,w.bottom-=k.y,
w.left-=k.x);return Cd(b,c,d,e,w,g,h)}
function Cd(a,b,c,d,f,e,g){a=a.c();var h=0,k=(c&4&&ac(b)?c^2:c)&-5;c=cc(b);g=g?g.c():c.c();if(d||0!=k)k&2?a.x-=g.width+(d?d.right:0):d&&(a.x+=d.left),k&1?a.y-=g.height+(d?d.bottom:0):d&&(a.y+=d.top);if(e&&(f?(h=a,d=0,65==(e&65)&&(h.x<f.left||h.x>=f.right)&&(e&=-2),132==(e&132)&&(h.y<f.top||h.y>=f.bottom)&&(e&=-5),h.x<f.left&&e&1&&(h.x=f.left,d|=1),h.x<f.left&&h.x+g.width>f.right&&e&16&&(g.width=Math.max(g.width-(h.x+g.width-f.right),0),d|=4),h.x+g.width>f.right&&e&1&&(h.x=Math.max(f.right-g.width,
f.left),d|=1),e&2&&(d=d|(h.x<f.left?16:0)|(h.x+g.width>f.right?32:0)),h.y<f.top&&e&4&&(h.y=f.top,d|=2),h.y<=f.top&&h.y+g.height<f.bottom&&e&32&&(g.height=Math.max(g.height-(f.top-h.y),0),h.y=f.top,d|=8),h.y>=f.top&&h.y+g.height>f.bottom&&e&32&&(g.height=Math.max(g.height-(h.y+g.height-f.bottom),0),d|=8),h.y+g.height>f.bottom&&e&4&&(h.y=Math.max(f.bottom-g.height,f.top),d|=2),e&8&&(d=d|(h.y<f.top?64:0)|(h.y+g.height>f.bottom?128:0)),h=d):h=256,h&496))return h;e=a;f=F&&(ab||hb)&&H("1.9");e instanceof
I?(a=e.x,e=e.y):(a=e,e=void 0);b.style.left=bc(a,f);b.style.top=bc(e,f);c==g||c&&g&&c.width==g.width&&c.height==g.height||(a=Mb(J(K(b))),!D||a&&H("8")?(b=b.style,F?b.MozBoxSizing="border-box":G?b.WebkitBoxSizing="border-box":b.boxSizing="border-box",b.width=Math.max(g.width,0)+"px",b.height=Math.max(g.height,0)+"px"):(c=b.style,a?(D?(a=hc(b,"paddingLeft"),f=hc(b,"paddingRight"),e=hc(b,"paddingTop"),d=hc(b,"paddingBottom"),a=new M(e,f,d,a)):(a=P(b,"paddingLeft"),f=P(b,"paddingRight"),e=P(b,"paddingTop"),
d=P(b,"paddingBottom"),a=new M(parseFloat(e),parseFloat(f),parseFloat(d),parseFloat(a))),!D||D&&9<=rb?(f=P(b,"borderLeftWidth"),e=P(b,"borderRightWidth"),d=P(b,"borderTopWidth"),b=P(b,"borderBottomWidth"),b=new M(parseFloat(d),parseFloat(e),parseFloat(b),parseFloat(f))):(f=jc(b,"borderLeft"),e=jc(b,"borderRight"),d=jc(b,"borderTop"),b=jc(b,"borderBottom"),b=new M(d,e,b,f)),c.pixelWidth=g.width-b.left-a.left-a.right-b.right,c.pixelHeight=g.height-b.top-a.top-a.bottom-b.bottom):(c.pixelWidth=g.width,
c.pixelHeight=g.height)));return h};function Dd(){}Dd.prototype.c=function(){};function Ed(a){this.e=a}A(Ed,Dd);Ed.prototype.c=function(a){Bd(this.e,0,a,2,void 0,new M(-2,0,0,0))};D&&H(8);var Fd={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","":"&#133;"," ":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Gd(a){return Fd[a]}var Hd=/[\x00\x22\x26\x27\x3c\x3e]/g;function Id(){return'<div><div class="tooltip-arrow"></div><div class="tooltip-inner">Tooltip on left</div></div>'}function Jd(){return'<div><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"></div></div></div>'};function Kd(a){Ec.call(this);this.e=a;this.c={}}A(Kd,Ec);var Ld=[];Kd.prototype.D=function(a,b,c,d,f){s(b)||(Ld[0]=b,b=Ld);for(var e=0;e<b.length;e++){var g=U(a,b[e],c||this.handleEvent,d||!1,f||this.e||this);if(!g)break;this.c[g.Oa]=g}return this};Kd.prototype.ua=function(a,b,c,d,f){if(s(b))for(var e=0;e<b.length;e++)this.ua(a,b[e],c,d,f);else c=c||this.handleEvent,f=f||this.e||this,c=Xc(c),d=!!d,b=Hc(a)?Pc(a.M,String(b),c,d,f):a?(a=Zc(a))?Pc(a,b,c,d,f):null:null,b&&(cd(b),delete this.c[b.Oa]);return this};
Kd.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Od(a,b){W.call(this);this.m=new Kd(this);this.ba(a||null);b&&(this.Z=b)}A(Od,W);l=Od.prototype;l.j=null;l.v=!1;l.Ca=-1;l.Z="toggle_display";l.ba=function(a){if(this.v)throw Error("Can not change this state of the popup while showing.");this.j=a};function Pd(a,b,c){a.F=b;a.A=c}
function Qd(a,b){a.F&&a.F.stop();a.A&&a.A.stop();if(b){if(!a.v&&a.Fa()){if(!a.j)throw Error("Caller must call setElement before trying to show the popup");a.R();var c=K(a.j);a.m.D(c,"mousedown",a.Ta,!0);if(D){var d;try{d=c.activeElement}catch(f){}for(;d&&"IFRAME"==d.nodeName;){try{var e=d.contentDocument||d.contentWindow.document}catch(g){break}c=e;d=c.activeElement}a.m.D(c,"mousedown",a.Ta,!0);a.m.D(c,"deactivate",a.Sa)}else a.m.D(c,"blur",a.Sa);"toggle_display"==a.Z?a.Ha():"move_offscreen"==a.Z&&
a.R();a.v=!0;a.Ca=z();a.F?(bd(a.F,"end",a.pa,!1,a),a.F.ya()):a.pa()}}else Rd(a)}l.R=aa;function Rd(a,b){if(a.v&&X(a,{type:"beforehide",target:b})){if(a.m){var c=a.m;Pa(c.c,cd);c.c={}}a.v=!1;z();a.A?(bd(a.A,"end",la(a.La,b),!1,a),a.A.ya()):a.La(b)}}l.La=function(a){"toggle_display"==this.Z?this.hb():"move_offscreen"==this.Z&&(this.j.style.top="-10000px");this.O(a)};l.Ha=function(){this.j.style.visibility="visible";fc(this.j,!0)};l.hb=function(){this.j.style.visibility="hidden";fc(this.j,!1)};
l.Fa=function(){return X(this,"beforeshow")};l.pa=function(){X(this,"show")};l.O=function(a){X(this,{type:"hide",target:a})};l.Ta=function(a){a=a.target;L(this.j,a)||150>z()-this.Ca||Rd(this,a)};l.Sa=function(a){var b=K(this.j);if("undefined"!=typeof document.activeElement){if(a=b.activeElement,!a||L(this.j,a)||"BODY"==a.tagName)return}else if(a.target!=b)return;150>z()-this.Ca||Rd(this)};function Sd(a,b,c){this.e=a;this.f=b;this.h=c}A(Sd,Dd);Sd.prototype.c=function(a,b,c){Bd(this.e,this.f,a,b,void 0,c,this.h)};function Td(a,b){this.e=a instanceof I?a:new I(a,b)}A(Td,Dd);Td.prototype.c=function(a,b,c,d){Bd(Xb(a),0,a,b,this.e,c,null,d)};function Ud(a,b){this.sa=4;this.X=b||void 0;Od.call(this,a)}A(Ud,Od);function Vd(a,b){a.X=b||void 0;a.v&&a.R()}Ud.prototype.R=function(){if(this.X){var a=!this.v&&"move_offscreen"!=this.Z,b=this.j;a&&(b.style.visibility="hidden",fc(b,!0));this.X.c(b,this.sa,this.pb);a&&fc(b,!1)}};function Wd(a){if("function"==typeof a.P)return a.P();if(v(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Qa(a)};function Xd(a,b){this.e={};this.t=[];this.h=this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)Yd(this,arguments[d],arguments[d+1])}else if(a){if(a instanceof Xd)Zd(a),d=a.t.concat(),c=a.P();else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=Qa(a)}for(f=0;f<d.length;f++)Yd(this,d[f],c[f])}}Xd.prototype.P=function(){Zd(this);for(var a=[],b=0;b<this.t.length;b++)a.push(this.e[this.t[b]]);return a};
Xd.prototype.clear=function(){this.e={};this.h=this.f=this.t.length=0};function Zd(a){if(a.f!=a.t.length){for(var b=0,c=0;b<a.t.length;){var d=a.t[b];Object.prototype.hasOwnProperty.call(a.e,d)&&(a.t[c++]=d);b++}a.t.length=c}if(a.f!=a.t.length){for(var f={},c=b=0;b<a.t.length;)d=a.t[b],Object.prototype.hasOwnProperty.call(f,d)||(a.t[c++]=d,f[d]=1),b++;a.t.length=c}}function Yd(a,b,c){Object.prototype.hasOwnProperty.call(a.e,b)||(a.f++,a.t.push(b),a.h++);a.e[b]=c}Xd.prototype.c=function(){return new Xd(this)};function $d(a){this.e=new Xd;if(a){a=Wd(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];Yd(this.e,ae(d),d)}}}function ae(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+fa(a):b.substr(0,1)+a}$d.prototype.clear=function(){this.e.clear()};$d.prototype.contains=function(a){a=ae(a);return Object.prototype.hasOwnProperty.call(this.e.e,a)};$d.prototype.P=function(){return this.e.P()};$d.prototype.c=function(){return new $d(this)};function be(a,b,c){this.k=c||(a?J(xb(a)):J());Ud.call(this,this.k.e("div",{style:"position:absolute;display:none;"}));this.e=new I(1,1);this.c=new $d;a&&ce(this,a);null!=b&&Fb(this.j,b)}A(be,Ud);var de=[];l=be.prototype;l.r=null;l.className="goog-tooltip";l.Aa=0;function ce(a,b){var c=b=xb(b);Yd(a.c.e,ae(c),c);U(b,"mouseover",a.ja,!1,a);U(b,"mouseout",a.T,!1,a);U(b,"mousemove",a.S,!1,a);U(b,"focus",a.Pa,!1,a);U(b,"blur",a.T,!1,a)}
function ee(a,b){V(b,"mouseover",a.ja,!1,a);V(b,"mouseout",a.T,!1,a);V(b,"mousemove",a.S,!1,a);V(b,"focus",a.Pa,!1,a);V(b,"blur",a.T,!1,a)}l.wa=function(){return this.Aa};l.ba=function(a){var b=this.j;b&&b&&b.parentNode&&b.parentNode.removeChild(b);be.B.ba.call(this,a);a&&(b=this.k.c.body,b.insertBefore(a,b.lastChild))};function fe(a){return a.w?a.v?4:1:a.n?3:a.v?2:0}l.la=function(a){if(!this.v)return!1;var b=S(this.j),c=cc(this.j);return b.x<=a.x&&a.x<=b.x+c.width&&b.y<=a.y&&a.y<=b.y+c.height};
l.Fa=function(){if(!Od.prototype.Fa.call(this))return!1;if(this.anchor)for(var a,b=0;a=de[b];b++)L(a.j,this.anchor)||Qd(a,!1);C(de,this)||de.push(this);a=this.j;a.className=this.className;ge(this);U(a,"mouseover",this.za,!1,this);U(a,"mouseout",this.Qa,!1,this);he(this);return!0};
l.O=function(){Ga(de,this);for(var a=this.j,b,c=0;b=de[c];c++)b.anchor&&L(a,b.anchor)&&Qd(b,!1);this.Ka&&ie(this.Ka);V(a,"mouseover",this.za,!1,this);V(a,"mouseout",this.Qa,!1,this);this.anchor=void 0;0==fe(this)&&(this.ra=!1);Od.prototype.O.call(this)};l.Da=function(a,b){this.anchor==a&&this.c.contains(this.anchor)&&(this.ra||!this.rb?(Qd(this,!1),this.v||(this.anchor=a,Vd(this,b||je(this,0)),Qd(this,!0))):this.anchor=void 0);this.w=void 0};
l.Ra=function(a){this.n=void 0;a==this.anchor&&(null!=this.r&&(this.r==this.j||this.c.contains(this.r))||this.f&&this.f.r||Qd(this,!1))};function ke(a,b){var c=Nb(a.k);a.e.x=b.clientX+c.x;a.e.y=b.clientY+c.y}l.ja=function(a){var b=le(this,a.target);this.r=b;ge(this);b!=this.anchor&&(this.anchor=b,me(this,b),ne(this),ke(this,a))};function le(a,b){try{for(;b&&!a.c.contains(b);)b=b.parentNode;return b}catch(c){return null}}l.S=function(a){ke(this,a);this.ra=!0};
l.Pa=function(a){this.r=a=le(this,a.target);this.ra=!0;if(this.anchor!=a){this.anchor=a;var b=je(this,1);ge(this);me(this,a,b);ne(this)}};function je(a,b){if(0==b){var c=a.e.c();return new oe(c)}return new pe(a.r)}function ne(a){if(a.anchor)for(var b,c=0;b=de[c];c++)L(b.j,a.anchor)&&(b.f=a,a.Ka=b)}l.T=function(a){var b=le(this,a.target),c=le(this,a.Q);b!=c&&(b==this.r&&(this.r=null),he(this),this.ra=!1,!this.v||a.Q&&L(this.j,a.Q)?this.anchor=void 0:ie(this))};
l.za=function(){var a=this.j;this.r!=a&&(ge(this),this.r=a)};l.Qa=function(a){var b=this.j;this.r!=b||a.Q&&L(b,a.Q)||(this.r=null,ie(this))};function me(a,b,c){a.w||(a.w=jd(x(a.Da,a,b,c),500))}function he(a){a.w&&(m.clearTimeout(a.w),a.w=void 0)}function ie(a){2==fe(a)&&(a.n=jd(x(a.Ra,a,a.anchor),a.wa()))}function ge(a){a.n&&(m.clearTimeout(a.n),a.n=void 0)}function oe(a,b){Td.call(this,a,b)}A(oe,Td);
oe.prototype.c=function(a,b,c){b=Xb(a);b=$b(b);c=c?new M(c.top+10,c.right,c.bottom,c.left+10):new M(10,0,0,10);Cd(this.e,a,4,c,b,9)&496&&Cd(this.e,a,4,c,b,5)};function pe(a){Sd.call(this,a,3)}A(pe,Sd);pe.prototype.c=function(a,b,c){var d=new I(10,0);Bd(this.e,this.f,a,b,d,c,9)&496&&Bd(this.e,2,a,1,d,c,5)};function qe(a,b,c){be.call(this,a,b,c)}A(qe,be);l=qe.prototype;l.va=!1;l.da=!1;l.pa=function(){qe.B.pa.call(this);this.J=Tb(ec(this.j));this.anchor&&(this.Ia=Tb(ec(this.anchor)));this.da=this.va;U(this.k.c,"mousemove",this.S,!1,this)};l.O=function(){V(this.k.c,"mousemove",this.S,!1,this);this.Ia=this.J=null;this.da=!1;qe.B.O.call(this)};
l.la=function(a){if(this.U){var b=S(this.j),c=cc(this.j);return b.x-this.U.left<=a.x&&a.x<=b.x+c.width+this.U.right&&b.y-this.U.top<=a.y&&a.y<=b.y+c.height+this.U.bottom}return qe.B.la.call(this,a)};function re(a,b){if(a.Ia&&a.Ia.contains(b)||a.la(b))return!0;var c=a.f;return!!c&&c.la(b)}l.Ra=function(a){this.n=void 0;a!=this.anchor||re(this,this.e)||this.r||this.f&&this.f.r||F&&0==this.e.x&&0==this.e.y||Qd(this,!1)};
l.S=function(a){var b=this.v;if(this.J){var c=Nb(this.k),c=new I(a.clientX+c.x,a.clientY+c.y);re(this,c)?b=!1:this.da&&(b=Sb(this.J,c)>=Sb(this.J,this.e))}if(b){if(ie(this),this.r=null,b=this.f)b.r=null}else 3==fe(this)&&ge(this);qe.B.S.call(this,a)};l.za=function(){this.r!=this.j&&(this.da=!1,this.r=this.j)};l.wa=function(){return this.da?100:qe.B.wa.call(this)};function Z(a,b,c,d){be.call(this,null,null,c);da(a)?this.Ba=a:this.Ja=a;this.Za=!1!=b;this.ta=[];this.$a=d||(c?c.c:document);U(this.$a,"mouseover",this.gb,!1,this)}A(Z,qe);l=Z.prototype;l.Ba=function(a){return a.tagName in this.Ja&&!!a.getAttribute(this.Ja[a.tagName])};l.gb=function(a){if(a=a.target)this.Ba(a)?(Vd(this,null),se(this,a)):this.Za&&(a=Lb(a,x(this.Ba,this),!1,this.qb))&&(Vd(this,null),se(this,a))};
function se(a,b){if(b==a.h)ge(a);else if(b!=a.anchor){if(1==fe(a)||4==fe(a))he(a),te(a);var c=new ue("trigger",a,b,void 0);a.c.contains(b)||(ce(a,b),a.ta.push(b));a.anchor=b;X(a,c)?me(a,b,a.X):te(a)}}function ve(a,b){var c=Ba(a.ta,b);if(-1!=c){if(b){var d=xb(b);ee(a,d);var f=a.c.e,d=ae(d);Object.prototype.hasOwnProperty.call(f.e,d)&&(delete f.e[d],f.f--,f.h++,f.t.length>2*f.f&&Zd(f))}else{for(var f=a.c.P(),e=0;d=f[e];e++)ee(a,d);a.c.clear()}a.ta.splice(c,1)}}
function te(a){X(a,new ue("canceltrigger",a,a.anchor||null));ve(a,a.anchor);delete a.anchor}l.O=function(){Z.B.O.call(this);null!=this.h&&ve(this,this.h);this.h=null};l.ja=function(a){var b=le(this,a.target);b&&b!=this.anchor?se(this,b):Z.B.ja.call(this,a)};l.T=function(a){var b=this.anchor,c=fe(this);Z.B.T.call(this,a);c==fe(this)||1!=c&&4!=c||(this.anchor=b,te(this))};l.Da=function(a,b){Z.B.Da.call(this,a,b);this.v?(a!=this.h&&ve(this,this.h),this.h=a):(he(this),te(this))};
function ue(a,b,c,d){T.call(this,a,b);this.anchor=c;this.data=d}A(ue,T);function we(){Z.call(this,function(a){return C(Ja(a),"line")&&a.getAttribute("data-linenum")},!0);var a=Ob(Id);this.ba(a);a.style.display="none";this.sa=2;this.v&&this.R();this.className="tooltip fade left in";this.va=!0;this.Aa=500;nc()?Pd(this,Ad(a,"ease-out",0,1),Ad(a,"ease-in",1,0)):Pd(this,new yd(a,150),new xd(a,150));U(this,"trigger",function(b){Vd(this,new Ed(b.anchor));b=b.anchor.getAttribute("data-linenum");Ab("tooltip-inner",a).innerHTML="#"+b;return!0},!1,this)}A(we,Z);
we.prototype.Ha=function(){var a=this.j;a.style.visibility="visible";a.style.display="block"};function xe(a){this.e=a}A(xe,Dd);xe.prototype.c=function(a){var b=ec(a),c=ec(this.e);Bd(this.e,0,a,1,void 0,new M(0,0,0,(c.width-b.width)/2))};function ye(){Z.call(this,function(a){return C(Ja(a),"note-link")},!1);this.ia={};ze(this);var a=Ob(Jd);this.ba(a);a.style.display="none";this.sa=2;this.v&&this.R();this.className="popover fade top in";this.va=!0;this.Aa=500;nc()?Pd(this,Ad(a,"ease-out",0,1),Ad(a,"ease-in",1,0)):Pd(this,new yd(a,150),new xd(a,150));U(this,"trigger",function(b){Vd(this,new xe(b.anchor));b=b.anchor.getAttribute("id");Ab("popover-content",a).innerHTML=this.ia[b].content;Ab("popover-title",a).innerHTML="Примечание "+
this.ia[b].lb;return!0},!1,this)}A(ye,Z);ye.prototype.ia=null;ye.prototype.Ha=function(){var a=this.j;a.style.visibility="visible";a.style.display="block"};function ze(a){Ca(yb("footnotes"),function(a){Ca(zb("li",null,a),function(a){var b=a.getAttribute("data-for");b&&(this.ia[b]={lb:Ib(xb(b)),content:a.innerHTML})},this);a&&a.parentNode&&a.parentNode.removeChild(a)},a)};var $=new function(){function a(a){return a.replace(/&/gm,"&amp;").replace(/</gm,"&lt;").replace(/>/gm,"&gt;")}function b(a,c){return Array.prototype.map.call(a.childNodes,function(a){return 3==a.nodeType?c?a.nodeValue.replace(/\n/g,""):a.nodeValue:"BR"==a.nodeName?"\n":b(a,c)}).join("")}function c(a){a=(a.className+" "+a.parentNode.className).split(/\s+/);a=a.map(function(a){return a.replace(/^language-/,"")});for(var b=0;b<a.length;b++)if(k[a[b]]||"no-highlight"==a[b])return a[b]}function d(a){var b=
[];(function t(a,c){for(var d=a.firstChild;d;d=d.nextSibling)3==d.nodeType?c+=d.nodeValue.length:"BR"==d.nodeName?c+=1:1==d.nodeType&&(b.push({event:"start",offset:c,oa:d}),c=t(d,c),b.push({event:"stop",offset:c,oa:d}));return c})(a,0);return b}function f(b,c,d){function f(b){return"<"+b.nodeName+Array.prototype.map.call(b.attributes,function(b){return" "+b.nodeName+'="'+a(b.value)+'"'}).join("")+">"}for(var e=0,g="",h=[];b.length||c.length;){var p=(b.length&&c.length?b[0].offset!=c[0].offset?b[0].offset<
c[0].offset?b:c:"start"==c[0].event?b:c:b.length?b:c).splice(0,1)[0],g=g+a(d.substr(e,p.offset-e)),e=p.offset;if("start"==p.event)g+=f(p.oa),h.push(p.oa);else if("stop"==p.event){var k,u=h.length;do u--,k=h[u],g+="</"+k.nodeName.toLowerCase()+">";while(k!=p.oa);for(h.splice(u,1);u<h.length;)g+=f(h[u]),u++}}return g+a(d.substr(e))}function e(a){function b(c,d){return RegExp(c,"m"+(a.$?"i":"")+(d?"g":""))}function c(a,d){if(!a.bb){a.bb=!0;var f=[];if(a.l){var e={},g=function(a,b){b.split(" ").forEach(function(b){b=
b.split("|");e[b[0]]=[a,b[1]?Number(b[1]):1];f.push(b[0])})};a.ma=b(a.kb||"[a-zA-Z][a-zA-Z0-9_]*",!0);if("string"==typeof a.l)g("keyword",a.l);else for(var h in a.l)a.l.hasOwnProperty(h)&&g(h,a.l[h]);a.l=e}d&&(a.ea&&(a.d="\\b("+f.join("|")+")\\s"),a.ab=b(a.d?a.d:"\\B|\\b"),a.end||a.H||(a.end="\\B|\\b"),a.end&&(a.eb=b(a.end)),a.Y=a.end||"",a.H&&d.Y&&(a.Y+=(a.end?"|":"")+d.Y));a.o&&(a.ib=b(a.o));void 0===a.g&&(a.g=1);a.contains||(a.contains=[]);for(g=0;g<a.contains.length;g++)"self"==a.contains[g]&&
(a.contains[g]=a),c(a.contains[g],a);a.W&&c(a.W,d);h=[];for(g=0;g<a.contains.length;g++)h.push(a.contains[g].d);a.Y&&h.push(a.Y);a.o&&h.push(a.o);a.Xa=h.length?b(h.join("|"),!0):{exec:function(){return null}}}}c(a)}function g(b,c){function d(a,b){if(a.end&&a.eb.test(b))return a;if(a.H)return d(a.parent,b)}function f(){var b;if(void 0!==p.L)p.L&&!k[p.L]?b=a(y):(b=p.L?g(p.L,y):h(y),0<p.g&&(R+=b.K,u+=b.g),b='<span class="'+b.language+'">'+b.value+"</span>");else if(b=a(y),p.l){var c="",d=0;p.ma.lastIndex=
0;for(var e=p.ma.exec(b);e;)c+=b.substr(d,e.index-d),d=ha.$?e[0].toLowerCase():e[0],(d=p.l.hasOwnProperty(d)&&p.l[d])?(R+=d[1],c+='<span class="'+d[0]+'">'+e[0]+"</span>"):c+=e[0],d=p.ma.lastIndex,e=p.ma.exec(b);b=c+b.substr(d)}return b}function E(b,c){var d=b.className?'<span class="'+b.className+'">':"";b.qa?(w+=d,y=""):b.fb?(w+=a(c)+d,y=""):(w+=d,y=c);p=Object.create(b,{parent:{value:p}});u+=b.g}function N(b,c){y+=b;if(void 0===c)return w+=f(),0;var e;a:{e=p;for(var g=0;g<e.contains.length;g++){var h=
e.contains[g].ab.exec(c);if(h&&0==h.index){e=e.contains[g];break a}}e=void 0}if(e)return w+=f(),E(e,c),e.qa?0:c.length;if(e=d(p,c)){e.Ga||e.ha||(y+=c);w+=f();do p.className&&(w+="</span>"),p=p.parent;while(p!=e.parent);e.ha&&(w+=a(c));y="";e.W&&E(e.W,"");return e.Ga?0:c.length}if(p.o&&p.ib.test(c))throw"Illegal";y+=c;return c.length||1}var ha=k[b];e(ha);var p=ha,y="",u=0,R=0,w="";try{for(var Xa,Md,Ya=0;;){p.Xa.lastIndex=Ya;Xa=p.Xa.exec(c);if(!Xa)break;Md=N(c.substr(Ya,Xa.index-Ya),Xa[0]);Ya=Xa.index+
Md}N(c.substr(Ya));return{g:u,K:R,value:w,language:b}}catch(Nd){if("Illegal"==Nd)return{g:0,K:0,value:a(c)};throw Nd;}}function h(b){var c={K:0,g:0,value:a(b)},d=c,f;for(f in k)if(k.hasOwnProperty(f)){var e=g(f,b);e.language=f;e.K+e.g>d.K+d.g&&(d=e);e.K+e.g>c.K+c.g&&(d=c,c=e)}d.language&&(c.aa=d);return c}var k={};this.f=k;this.J=function(a){var e=b(a,void 0),k=c(a);if("no-highlight"!=k){var t=k?g(k,e):h(e),k=t.language,E=d(a);if(E.length){var N=document.createElement("pre");N.innerHTML=t.value;t.value=
f(E,d(N),e)}t.value=t.value;e=a.className;e.match("(\\s|^)(language-)?"+k+"(\\s|$)")||(e=e?e+" "+k:k);a.innerHTML=t.value;a.className=e;a.result={language:k,jb:t.K,ob:t.g};t.aa&&(a.aa={language:t.aa.language,jb:t.aa.K,ob:t.aa.g})}};this.c={d:"\\\\[\\s\\S]",g:0};this.k={className:"string",d:"'",end:"'",o:"\\n",contains:[this.c],g:0};this.h={className:"string",d:'"',end:'"',o:"\\n",contains:[this.c],g:0};this.m={className:"comment",d:"//",end:"$"};this.e={className:"comment",d:"/\\*",end:"\\*/"};this.A=
{className:"comment",d:"#",end:"$"};this.w={className:"number",d:"\\b\\d+(\\.\\d+)?",g:0};this.n={className:"number",d:"(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)",g:0};this.F={className:"number",d:"\\b(0b[01]+)",g:0};this.D=function(a,b){var c={},d;for(d in a)c[d]=a[d];if(b)for(d in b)c[d]=b[d];return c}},Ae={className:"variable",d:"\\$+[a-zA-Z_-ÿ][a-zA-Z0-9_-ÿ]*"},Be=[$.D($.k,{o:null}),$.D($.h,{o:null}),{className:"string",d:'b"',end:'"',contains:[$.c]},{className:"string",
d:"b'",end:"'",contains:[$.c]}],Ce=[$.F,$.n],De={className:"title",d:"[a-zA-Z_][a-zA-Z0-9_]*"};
$.f.php={$:!0,l:"and include_once list abstract global private echo interface as static endswitch array null if endwhile or const for endforeach self var while isset public protected exit foreach throw elseif include __FILE__ empty require_once do xor return implements parent clone use __CLASS__ __LINE__ else break print eval new catch __METHOD__ case exception php_user_filter default die require __FUNCTION__ enddeclare final try this switch continue endfor endif declare unset true false namespace trait goto instanceof insteadof __DIR__ __NAMESPACE__ __halt_compiler",contains:[$.m,
$.A,{className:"comment",d:"/\\*",end:"\\*/",contains:[{className:"phpdoc",d:"\\s@[A-Za-z]+"}]},{className:"comment",fb:!0,d:"__halt_compiler.+?;",H:!0},{className:"string",d:"<<<['\"]?\\w+['\"]?$",end:"^\\w+;",contains:[$.c]},{className:"preprocessor",d:"<\\?php",g:10},{className:"preprocessor",d:"\\?>"},Ae,{className:"function",ea:!0,end:"{",l:"function",o:"\\$|\\[|%",contains:[De,{className:"params",d:"\\(",end:"\\)",contains:["self",Ae,$.e].concat(Be).concat(Ce)}]},{className:"class",ea:!0,end:"{",
l:"class",o:"[:\\(\\$]",contains:[{ea:!0,H:!0,l:"extends",contains:[De]},De]},{d:"=>"}].concat(Be).concat(Ce)};var Ee={className:"function",d:"[a-zA-Z][a-zA-Z0-9_]*\\(",end:"\\)",contains:[$.w,$.k,$.h]};
$.f.css={$:!0,o:"[=/|']",contains:[$.e,{className:"id",d:"\\#[A-Za-z0-9_-]+"},{className:"class",d:"\\.[A-Za-z0-9_-]+",g:0},{className:"attr_selector",d:"\\[",end:"\\]",o:"$"},{className:"pseudo",d:":(:)?[a-zA-Z0-9\\_\\-\\+\\(\\)\\\"\\']+"},{className:"at_rule",d:"@(font-face|page)",kb:"[a-z-]+",l:"font-face page"},{className:"at_rule",d:"@",end:"[{;]",ha:!0,l:"import page media charset",contains:[Ee,$.k,$.h,$.w]},{className:"tag",d:"[a-zA-Z][a-zA-Z0-9_]*",g:0},{className:"rules",d:"{",end:"}",o:"[^\\s]",
g:0,contains:[$.e,{className:"rule",d:"[^\\s]",qa:!0,end:";",H:!0,contains:[{className:"attribute",d:"[A-Z\\_\\.\\-]+",end:":",ha:!0,o:"[^\\s]",W:{className:"value",H:!0,ha:!0,contains:[Ee,$.w,$.h,$.k,$.e,{className:"hexcolor",d:"\\#[0-9A-F]+"},{className:"important",d:"!important"}]}}]}]}]};var Fe={className:"type",d:"\\b[A-Z][\\w']*",g:0},Ge={className:"container",d:"\\(",end:"\\)",contains:[{className:"type",d:"\\b[A-Z][\\w]*(\\((\\.\\.|,|\\w+)\\))?"},{className:"title",d:"[_a-z][\\w']*"}]};
$.f.haskell={l:"let in if then else case of where do module import hiding qualified type data newtype deriving class instance not as foreign ccall safe unsafe",contains:[{className:"comment",d:"--",end:"$"},{className:"preprocessor",d:"{-#",end:"#-}"},{className:"comment",contains:["self"],d:"{-",end:"-}"},{className:"string",d:"\\s+'",end:"'",contains:[$.c],g:0},$.h,{className:"import",d:"\\bimport",end:"$",l:"import qualified as hiding",contains:[Ge],o:"\\W\\.|;"},{className:"module",d:"\\bmodule",
end:"where",l:"module where",contains:[Ge],o:"\\W\\.|;"},{className:"class",d:"\\b(class|instance)",end:"where",l:"class where instance",contains:[Fe]},{className:"typedef",d:"\\b(data|(new)?type)",end:"$",l:"data type newtype deriving",contains:[Fe,Ge,{className:"container",d:"{",end:"}",contains:Ge.contains}]},$.n,{className:"shebang",d:"#!\\/usr\\/bin\\/env runhaskell",end:"$"},Fe,{className:"title",d:"^[_a-z][\\w']*"}]};
$.f.sql={$:!0,contains:[{className:"operator",d:"(begin|start|commit|rollback|savepoint|lock|alter|create|drop|rename|call|delete|do|handler|insert|load|replace|select|truncate|update|set|show|pragma|grant)\\b(?!:)",end:";",H:!0,l:{keyword:"all partial global month current_timestamp using go revoke smallint indicator end-exec disconnect zone with character assertion to add current_user usage input local alter match collate real then rollback get read timestamp session_user not integer bit unique day minute desc insert execute like ilike|2 level decimal drop continue isolation found where constraints domain right national some module transaction relative second connect escape close system_user for deferred section cast current sqlstate allocate intersect deallocate numeric public preserve full goto initially asc no key output collation group by union session both last language constraint column of space foreign deferrable prior connection unknown action commit view or first into float year primary cascaded except restrict set references names table outer open select size are rows from prepare distinct leading create only next inner authorization schema corresponding option declare precision immediate else timezone_minute external varying translation true case exception join hour default double scroll value cursor descriptor values dec fetch procedure delete and false int is describe char as at in varchar null trailing any absolute current_time end grant privileges when cross check write current_date pad begin temporary exec time update catalog user sql date on identity timezone_hour natural whenever interval work order cascade diagnostics nchar having left call do handler load replace truncate start lock show pragma exists number",
aggregate:"count sum min max avg"},contains:[{className:"string",d:"'",end:"'",contains:[$.c,{d:"''"}],g:0},{className:"string",d:'"',end:'"',contains:[$.c,{d:'""'}],g:0},{className:"string",d:"`",end:"`",contains:[$.c]},$.n]},$.e,{className:"comment",d:"--",end:"$"}]};
var He={H:!0,contains:[{className:"attribute",d:"[A-Za-z0-9\\._:-]+",g:0},{d:'="',qa:!0,end:'"',contains:[{className:"value",d:'"',H:!0}]},{d:"='",qa:!0,end:"'",contains:[{className:"value",d:"'",H:!0}]},{d:"=",contains:[{className:"value",d:"[^\\s/>]+"}]}]};
$.f.xml={$:!0,contains:[{className:"pi",d:"<\\?",end:"\\?>",g:10},{className:"doctype",d:"<!DOCTYPE",end:">",g:10,contains:[{d:"\\[",end:"\\]"}]},{className:"comment",d:"\x3c!--",end:"--\x3e",g:10},{className:"cdata",d:"<\\!\\[CDATA\\[",end:"\\]\\]>",g:10},{className:"tag",d:"<style(?=\\s|>|$)",end:">",l:{title:"style"},contains:[He],W:{end:"</style>",Ga:!0,L:"css"}},{className:"tag",d:"<script(?=\\s|>|$)",end:">",l:{title:"script"},contains:[He],W:{end:"\x3c/script>",Ga:!0,L:"javascript"}},{d:"<%",
end:"%>",L:"vbscript"},{className:"tag",d:"</?",end:"/?>",contains:[{className:"title",d:"[^ />]+"},He]}]};var Ie={className:"variable",d:"\\$[a-zA-Z0-9_#]+"},Je={className:"variable",d:"\\${([^}]|\\\\})+}"},Ke={className:"string",d:'"',end:'"',o:"\\n",contains:[$.c,Ie,Je],g:0},Le={className:"string",d:"'",end:"'",contains:[{d:"''"}],g:0},Me={className:"test_condition",d:"",end:"",contains:[Ke,Le,Ie,Je],l:{vb:"true false"},g:0};
$.f.bash={l:{keyword:"if then else elif fi for break continue while in do done echo exit return set declare",literal:"true false"},contains:[{className:"shebang",d:"(#!\\/bin\\/bash)|(#!\\/bin\\/sh)",g:10},Ie,Je,$.A,Ke,Le,$.D(Me,{d:"\\[ ",end:" \\]",g:0}),$.D(Me,{d:"\\[\\[ ",end:" \\]\\]"})]};
$.f.javascript={l:{keyword:"in if for while finally var new function do return void else break catch instanceof with throw case default try this switch continue typeof delete let yield const",literal:"true false null undefined NaN Infinity"},contains:[$.k,$.h,$.m,$.e,$.n,{d:"(!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~|\\b(case|return|throw)\\b)\\s*",l:"return throw case",contains:[$.m,$.e,{className:"regexp",
d:"/",end:"/[gim]*",o:"\\n",contains:[{d:"\\\\/"}]},{d:"<",end:">;",L:"xml"}],g:0},{className:"function",ea:!0,end:"{",l:"function",contains:[{className:"title",d:"[A-Za-z$_][0-9A-Za-z$_]*"},{className:"params",d:"\\(",end:"\\)",contains:[$.m,$.e],o:"[\"'\\(]"}],o:"\\[|%"}]};function Ne(){}Ne.prototype.h=function(){0!=Ib(this.e[0]).lastIndexOf("Считаем",0)&&(this.c.stop(),Ca(this.e,this.f,this))};Ne.prototype.f=function(a){a=zb("a",null,a);if(0!=a.length){var b=Ib(a[0]).match(/^(\d+) комментариев/);if(b&&(b=Number(b[1]),1!=Math.round(b%100/10))){var c=b%10;1==c?Fb(a[0],b+" комментарий"):2<=c&&4>=c&&Fb(a[0],b+" комментария")}}};var Oe=new Ne;(function(){function a(){d?Oa(c,["collapse","collapsing"],"in"):(Oa(c,["in","collapsing"],"collapse"),c.style.height=bc(1,!0))}var b=Ab("navbar-toggle-button"),c=Ab("navbar-collapsible-block"),d=!1;U(b,"click",function(){(d=!d)?(Oa(c,["collapse","in"],"collapsing"),c.style.height=bc(c.scrollHeight+1,!0)):(Ma(c,"collapse","in"),Ka(c,"collapsing"),c.style.height=bc(0,!0));nc()?setTimeout(a,350):a()})})();var Pe=zb("span","post-comments",void 0);
if(Pe.length){Oe.e=Pe;Oe.c=new hd(100);U(Oe.c,id,Oe.h,!1,Oe);var Qe=Oe.c;Qe.h=!0;Qe.c||(Qe.c=Qe.e.setTimeout(Qe.k,Qe.f),Qe.m=z())}
(function(){var a=zb("code","sourceCode",void 0),a=Ea(a,function(a){return a.parentNode instanceof HTMLPreElement});if(a.length){var b=new pc,c=new Cc;Ca(a,function(a){$.J(a);var f=a.innerHTML,e=null,g=!1,h=[],k,q,r;c.na=[];c.G=new oc;for(c.ca=[];f;){var n=f.match(g?zc:Ac),f=f.substring(n[0].length);if(g)if(n[1]){var t=n[1].toLowerCase();if(n[2]){n=n[3];switch(n.charCodeAt(0)){case 34:case 39:n=n.substring(1,n.length-1)}n=n.replace(vc,"").replace(wc,x(b.c,b))}else n=t;h.push(t,n)}else n[4]&&(void 0!==
q&&(r?c.Va&&c.Va(k,h):c.Ma&&c.Ma(k)),r&&q&12&&(e=null===e?f.toLowerCase():e.substring(e.length-f.length),g=e.indexOf("</"+k),0>g&&(g=f.length),q&4||c.nb&&f.substring(0,g).replace(sc,"&amp;$1").replace(tc,"&lt;").replace(uc,"&gt;"),f=f.substring(g)),k=q=r=void 0,h.length=0,g=!1);else if(n[1])Dc(c,n[0]);else if(n[3])r=!n[2],g=!0,k=n[3].toLowerCase(),q=rc.hasOwnProperty(k)?rc[k]:void 0;else if(n[4])Dc(c,n[4]);else if(n[5])switch(n[5]){case "<":Dc(c,"&lt;");break;case ">":Dc(c,"&gt;");break;default:Dc(c,
"&amp;")}}(f=c.G.toString())&&c.na.push(f);q="";f=c.na;e=f.length;for(h=0;h<e;h++)k=f[h],g=(0!=h?"\n":"")+'<span class="line" data-linenum="'+(h+1&&(h+1).ga&&(h+1).ga===ma?(h+1).content:String(h+1).replace(Hd,Gd))+'">',""==k?k="&nbsp;":k&&k.ga===na?(Aa("Tainted SanitizedContentKind.TEXT for |noAutoescape: `%s`",[k.content]),k="zSoyz"):k=String(k),q=q+(g+k+"</span>");a.innerHTML=Pb(q);Ka(a,"highlighted")})}return 0<a.length})()&&new we;new ye;
U(document,"keydown",function(a){if(a.ctrlKey){var b;37===a.keyCode?b=Ab("previous"):39===a.keyCode&&(b=Ab("next"));if(a=b)a=Kb(b);a&&(b=zb("a",null,b),b.length&&(document.location=b[0].getAttribute("href")))}});
