prose:
  siteurl: "http://dikmax.name"
  metadata:
    posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "New post"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "published"
        field:
          element: "button"
          on: "Published"
          off: "Unpublished"
