prose:
  siteurl: "http://dikmax.name"
  metadata:
    posts:
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "date"
        field:
          element: "text"
          date: "Date"
          value: CURRENT_DATETIME